export const Permissions = {
    USERS_VIEW: "users.view",
    USERS_CREATE: "users.create",
    USERS_UPDATE: "users.update",
    USERS_DELETE: "users.delete",
    USERS_MANAGE: "users.manage",

    ROLES_VIEW: "roles.view",
    ROLES_CREATE: "roles.create",
    ROLES_UPDATE: "roles.update",
    ROLES_DELETE: "roles.delete",

    GAMES_VIEW: "games.view",
    GAMES_CREATE: "games.create",
    GAMES_UPDATE: "games.update",
    GAMES_DELETE: "games.delete",

    TOURNAMENTS_VIEW: "tournaments.view",
    TOURNAMENTS_CREATE: "tournaments.create",
    TOURNAMENTS_UPDATE: "tournaments.update",
    TOURNAMENTS_DELETE: "tournaments.delete",
    TOURNAMENTS_MANAGE: "tournaments.manage",

    TEAMS_VIEW: "teams.view",
    TEAMS_CREATE: "teams.create",
    TEAMS_UPDATE: "teams.update",
    TEAMS_DELETE: "teams.delete",

    FORUM_VIEW: "forum.view",
    FORUM_CREATE_TOPIC: "forum.create_topic",
    FORUM_CREATE_POST: "forum.create_post",
    FORUM_MODERATE: "forum.moderate",

    APPEALS_VIEW: "appeals.view",
    APPEALS_CREATE: "appeals.create",
    APPEALS_ASSIGN: "appeals.assign",
    APPEALS_RESOLVE: "appeals.resolve",

    CONSTITUTION_VIEW: "constitution.view",
    CONSTITUTION_UPDATE: "constitution.update",

    RECIPES_VIEW: "recipes.view",
    RECIPES_CREATE: "recipes.create",
    RECIPES_DELETE: "recipes.delete",

    MOVIES_VIEW: "movies.view",
    MOVIES_CREATE: "movies.create",
    MOVIES_UPDATE: "movies.update",
    MOVIES_DELETE: "movies.delete",

    CINEMA_VIEW: "cinema.view",
    CINEMA_COMMENT: "cinema.comment",

    DASHBOARD_VIEW: "dashboard.view",
    LOGS_VIEW: "logs.view",
    NOTIFICATIONS_VIEW: "notifications.view",
    NOTIFICATIONS_SEND: "notifications.send",
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];

export const RolePermissions: Record<string, Permission[]> = {
    Administrator: Object.values(Permissions),
    Moderator: [
        Permissions.USERS_VIEW,
        Permissions.TOURNAMENTS_VIEW,
        Permissions.TEAMS_VIEW,
        Permissions.FORUM_VIEW,
        Permissions.FORUM_CREATE_TOPIC,
        Permissions.FORUM_CREATE_POST,
        Permissions.FORUM_MODERATE,
        Permissions.APPEALS_VIEW,
        Permissions.APPEALS_ASSIGN,
        Permissions.APPEALS_RESOLVE,
        Permissions.CONSTITUTION_VIEW,
        Permissions.CONSTITUTION_UPDATE,
        Permissions.RECIPES_VIEW,
        Permissions.RECIPES_CREATE,
        Permissions.MOVIES_VIEW,
        Permissions.MOVIES_CREATE,
        Permissions.CINEMA_VIEW,
        Permissions.CINEMA_COMMENT,
        Permissions.DASHBOARD_VIEW,
    ],
    Judge: [
        Permissions.TOURNAMENTS_VIEW,
        Permissions.TOURNAMENTS_MANAGE,
        Permissions.TEAMS_VIEW,
        Permissions.FORUM_VIEW,
        Permissions.FORUM_CREATE_TOPIC,
        Permissions.FORUM_CREATE_POST,
        Permissions.APPEALS_VIEW,
        Permissions.APPEALS_RESOLVE,
        Permissions.CONSTITUTION_VIEW,
        Permissions.RECIPES_VIEW,
        Permissions.RECIPES_CREATE,
        Permissions.MOVIES_VIEW,
        Permissions.MOVIES_CREATE,
        Permissions.CINEMA_VIEW,
        Permissions.CINEMA_COMMENT,
        Permissions.DASHBOARD_VIEW,
    ],
    Captain: [
        Permissions.TOURNAMENTS_VIEW,
        Permissions.TEAMS_VIEW,
        Permissions.TEAMS_CREATE,
        Permissions.FORUM_VIEW,
        Permissions.FORUM_CREATE_TOPIC,
        Permissions.FORUM_CREATE_POST,
        Permissions.APPEALS_VIEW,
        Permissions.APPEALS_CREATE,
        Permissions.CONSTITUTION_VIEW,
        Permissions.RECIPES_VIEW,
        Permissions.RECIPES_CREATE,
        Permissions.MOVIES_VIEW,
        Permissions.MOVIES_CREATE,
        Permissions.CINEMA_VIEW,
        Permissions.CINEMA_COMMENT,
        Permissions.DASHBOARD_VIEW,
    ],
    User: [
        Permissions.TOURNAMENTS_VIEW,
        Permissions.TEAMS_VIEW,
        Permissions.FORUM_VIEW,
        Permissions.FORUM_CREATE_TOPIC,
        Permissions.FORUM_CREATE_POST,
        Permissions.APPEALS_VIEW,
        Permissions.APPEALS_CREATE,
        Permissions.CONSTITUTION_VIEW,
        Permissions.RECIPES_VIEW,
        Permissions.MOVIES_VIEW,
        Permissions.CINEMA_VIEW,
        Permissions.CINEMA_COMMENT,
        Permissions.DASHBOARD_VIEW,
    ],
};
